version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: family-recipe
    container_name: family-recipe
    restart: unless-stopped
    ports:
      - "8006:80"
    volumes:
      - ./:/var/www/html

networks:
  default:
    driver: bridge
